# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### NumPy

Para importar numpy, utilize: 
import numpy as np


Você também pode utilizar: 
from numpy import *  . Isso evitará a utilização de np., mas este comando importará todos os módulos do NumPy.

Para atualizar o NumPy, abra o prompt de comando e digite: pip install numpy -U

In [1]:
# Importando o NumPy, este "as" é um apelido dado ao pacote para não precisar chamar o nome inteiro toda vez que for usa
import numpy as np

In [2]:
# Olhando a versão
np.__version__

'1.14.3'

## Criando Arrays

In [3]:
# Help
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [4]:
# Array criado a partir de uma lista, (unidimencional):
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho.
type(vetor1)

numpy.ndarray

In [7]:
# Usando métodos do array NumPy. Método que calcula soma acumulada
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [8]:
# Criando uma lista. Perceba como listas e arrays são objetos diferentes, com diferentes propriedades
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
type(lst)

list

In [11]:
# Imprimindo na tela um elemento específico no array
vetor1[0] 

0

In [12]:
# Alterando um elemento do array
vetor1[0] = 100

In [13]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [14]:
# Não é possível incluir elemento de outro tipo
vetor1[0] = 'Novo elemento'

ValueError: invalid literal for int() with base 10: 'Novo elemento'

In [15]:
# Verificando o formato do array, no caso a resposta (9,) indica ser um array unidimensional
print(vetor1.shape)

(9,)


## Funções NumPy

In [16]:
# A função arange (range) cria um vetor contendo uma progressão aritmética a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [17]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [18]:
# Verificando o tipo do objeto
type(vetor2)

numpy.ndarray

In [19]:
# Formato do array
np.shape(vetor2)

(9,)

In [20]:
print (vetor2.dtype)

float64


In [21]:
x = np.arange(1, 10, 0.25)
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [22]:
# Criando um array de mesmo elemento (zero neste casao)
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
# Retorna 1 nas posições em diagonal e 0 no restante, o 7 é o tamanho da matriz 7x7
z = np.eye(7)

In [28]:
z

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [29]:
# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))

In [30]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [31]:
# Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])

In [32]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [33]:
# Array de valores booleanos
b = np.array([True, False, False, True])

In [34]:
b

array([ True, False, False,  True])

In [35]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])

In [36]:
s

array(['Python', 'R', 'Julia'], dtype='<U6')

In [37]:
# O método linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado 
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [39]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


## Criando Matrizes

In [40]:
# Criando uma matriz
matriz = np.array([[1,2,3],[4,5,6]]) 

In [41]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [42]:
# O resultado indica uma matriz com 2 linhas e 3 colunas
print(matriz.shape)

(2, 3)


In [48]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2,3))

In [49]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [50]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [51]:
# A função matrix cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)

In [52]:
matriz2

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [53]:
type(matriz2)

numpy.matrixlib.defmatrix.matrix

In [54]:
# Formato da matriz, o resultado indicará uma matriz 3x3
np.shape(matriz2)

(3, 3)

In [55]:
matriz2.size

9

In [56]:
print(matriz2.dtype)

int32


In [58]:
# Verifica o tamanho de cada item da matriz que irá ocupar na memória
matriz2.itemsize

4

In [59]:
# 9 x 4 = 36
matriz2.nbytes

36

In [60]:
# Slicing da matriz
print(matriz2[2,1])

48


In [61]:
# Alterando um elemento da matriz
matriz2[1,0] = 100

In [62]:
matriz2

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [63]:
x = np.array([1, 2])  # NumPy decide o tipo dos dados, o Numpy decidira Int
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados, o Numpy decidirá float
z = np.array([1, 2], dtype=np.float64)  # Forçamos um tipo de dado em particular, no caso floats

print (x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [64]:
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)

In [65]:
matriz3

array([[24., 76.],
       [35., 89.]])

In [66]:
matriz3.itemsize

8

In [67]:
matriz3.nbytes

32

In [68]:
# Total de dimensões
matriz3.ndim

2

In [69]:
matriz3[1,1]

89.0

In [70]:
matriz3[1,1] = 100

In [71]:
matriz3

array([[ 24.,  76.],
       [ 35., 100.]])

## Usando o Método random() do NumPy

In [ ]:
print(np.random.rand(10))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
print(np.random.rand(10))

In [ ]:
plt.show((plt.hist(np.random.rand(1000))))

In [ ]:
print(np.random.randn(5,5))

In [ ]:
plt.show(plt.hist(np.random.randn(1000)))

In [ ]:
imagem = np.random.rand(30, 30)
plt.imshow(imagem, cmap = plt.cm.hot)    
plt.colorbar()    

## Operações com datasets

In [ ]:
import os
filename = os.path.join('iris.csv')

In [ ]:
# No Windows use !more iris.csv. Mac ou Linux use !head iris.csv
!head iris.csv
#!more iris.csv

In [ ]:
# Carregando um dataset para dentro de um array
arquivo = np.loadtxt(filename, delimiter=',', usecols=(0,1,2,3), skiprows=1)
print (arquivo)

In [ ]:
type(arquivo)

In [ ]:
# Gerando um plot a partir de um arquivo usando o NumPy
var1, var2 = np.loadtxt(filename, delimiter=',', usecols=(0,1), skiprows=1, unpack=True)
plt.show(plt.plot(var1, var2, 'o', markersize=8, alpha=0.75))

## Estatística

In [ ]:
# Criando um array
A = np.array([15, 23, 63, 94, 75])

In [ ]:
# Em estatística a média é o valor que aponta para onde mais se concentram os dados de uma distribuição.
np.mean(A)

In [ ]:
# O desvio padrão mostra o quanto de variação ou "dispersão" existe em 
# relação à média (ou valor esperado). 
# Um baixo desvio padrão indica que os dados tendem a estar próximos da média.
# Um desvio padrão alto indica que os dados estão espalhados por uma gama de valores.
np.std(A)

In [ ]:
# Variância de uma variável aleatória é uma medida da sua dispersão 
# estatística, indicando "o quão longe" em geral os seus valores se 
# encontram do valor esperado
np.var(A)

In [ ]:
d = np.arange(1, 10)

In [ ]:
d

In [ ]:
np.sum(d)

In [ ]:
# Retorna o produto dos elementos
np.prod(d)

In [ ]:
# Soma acumulada dos elementos
np.cumsum(d)

In [ ]:
a = np.random.randn(400,2)
m = a.mean(0)
print (m, m.shape)

In [ ]:
plt.plot(a[:,0], a[:,1], 'o', markersize=5, alpha=0.50)
plt.plot(m[0], m[1], 'ro', markersize=10)
plt.show()

## Outras Operações com Arrays

In [ ]:
# Slicing
a = np.diag(np.arange(3))

In [ ]:
a

In [ ]:
a[1, 1]

In [ ]:
a[1]

In [ ]:
b = np.arange(10)

In [ ]:
b

In [ ]:
# [start:end:step]
b[2:9:3] 

In [ ]:
# Comparação
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

In [ ]:
np.array_equal(a, b)

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
# Somando um elemento ao array
np.array([1, 2, 3]) + 1.5

In [ ]:
# Usando o método around
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [ ]:
b = np.around(a)

In [ ]:
b

In [ ]:
# Criando um array
B = np.array([1, 2, 3, 4])

In [ ]:
B

In [ ]:
# Copiando um array
C = B.flatten()

In [ ]:
C

In [ ]:
# Criando um array
v = np.array([1, 2, 3])

In [ ]:
# Adcionando uma dimensão ao array
v[:, np.newaxis], v[:,np.newaxis].shape, v[np.newaxis,:].shape

In [ ]:
# Repetindo os elementos de um array
np.repeat(v, 3)

In [ ]:
# Repetindo os elementos de um array
np.tile(v, 3)

In [ ]:
# Criando um array
w = np.array([5, 6])

In [ ]:
# Concatenando
np.concatenate((v, w), axis=0)

In [ ]:
# Copiando arrays
r = np.copy(v)

In [ ]:
r

Conheça a Formação Cientista de Dados, um programa completo, 100% online e 100% em português, com 340 horas, mais de 1.200 aulas em vídeos e 26 projetos, que vão ajudá-lo a se tornar um dos profissionais mais cobiçados do mercado de análise de dados. Clique no link abaixo, faça sua inscrição, comece hoje mesmo e aumente sua empregabilidade:

https://www.datascienceacademy.com.br/pages/formacao-cientista-de-dados

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>